<?php
/**
 * Database configuration — MariaDB/MySQL
 * Credentials are read from db_config.php (generated by install.php) or env vars.
 */
class Database {
    private string $host;
    private string $db_name;
    private string $username;
    private string $password;
    private int $port;
    private ?PDO $conn = null;
    private static ?array $dotenvCache = null;

    private array $defaults = [
        'host'     => 'localhost',
        'db_name'  => 'cerrajeria_express',
        'username' => 'root',
        'password' => '',
        'port'     => 3306,
    ];

    private static function loadDotEnv(): array {
        if (self::$dotenvCache !== null) {
            return self::$dotenvCache;
        }

        $paths = [
            __DIR__ . '/../.env',
            __DIR__ . '/../../.env',
            __DIR__ . '/../../../.env',
        ];

        $vars = [];
        foreach ($paths as $path) {
            if (!is_file($path) || !is_readable($path)) {
                continue;
            }

            $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            if ($lines === false) {
                continue;
            }

            foreach ($lines as $line) {
                $trimmed = trim($line);
                if ($trimmed === '' || str_starts_with($trimmed, '#')) {
                    continue;
                }
                if (str_starts_with($trimmed, 'export ')) {
                    $trimmed = trim(substr($trimmed, 7));
                }
                $pos = strpos($trimmed, '=');
                if ($pos === false) {
                    continue;
                }

                $key = trim(substr($trimmed, 0, $pos));
                $value = trim(substr($trimmed, $pos + 1));
                if ($key === '') {
                    continue;
                }

                $len = strlen($value);
                if ($len >= 2) {
                    $first = $value[0];
                    $last = $value[$len - 1];
                    if (($first === '"' && $last === '"') || ($first === "'" && $last === "'")) {
                        $value = substr($value, 1, -1);
                    }
                }

                if (!array_key_exists($key, $vars)) {
                    $vars[$key] = $value;
                }
            }
        }

        self::$dotenvCache = $vars;
        return self::$dotenvCache;
    }

    private function readEnv(string $key): ?string {
        $value = getenv($key);
        if ($value !== false && $value !== '') {
            return (string)$value;
        }

        $redirectKey = 'REDIRECT_' . $key;
        $redirectValue = getenv($redirectKey);
        if ($redirectValue !== false && $redirectValue !== '') {
            return (string)$redirectValue;
        }

        if (isset($_ENV[$key]) && $_ENV[$key] !== '') {
            return (string)$_ENV[$key];
        }

        if (isset($_ENV[$redirectKey]) && $_ENV[$redirectKey] !== '') {
            return (string)$_ENV[$redirectKey];
        }

        if (isset($_SERVER[$key]) && $_SERVER[$key] !== '') {
            return (string)$_SERVER[$key];
        }

        if (isset($_SERVER[$redirectKey]) && $_SERVER[$redirectKey] !== '') {
            return (string)$_SERVER[$redirectKey];
        }

        $dotenv = self::loadDotEnv();
        if (isset($dotenv[$key]) && $dotenv[$key] !== '') {
            return (string)$dotenv[$key];
        }

        if (isset($dotenv[$redirectKey]) && $dotenv[$redirectKey] !== '') {
            return (string)$dotenv[$redirectKey];
        }

        return null;
    }

    private function readEnvAny(array $keys): ?string {
        foreach ($keys as $key) {
            $value = $this->readEnv($key);
            if ($value !== null && $value !== '') {
                return $value;
            }
        }
        return null;
    }

    public function __construct() {
        $installed = [];
        $configFile = __DIR__ . '/db_config.php';
        if (file_exists($configFile)) {
            $loaded = include $configFile;
            if (is_array($loaded)) {
                $installed = $loaded;
            }
        }

        $this->host = $installed['host'] ?? $this->readEnvAny([
            'DB_HOST', 'MYSQL_HOST', 'MYSQLHOST'
        ]) ?? $this->defaults['host'];

        $this->db_name = $installed['db_name'] ?? $this->readEnvAny([
            'DB_NAME', 'DATABASE_NAME', 'MYSQL_DATABASE', 'MYSQLDATABASE'
        ]) ?? $this->defaults['db_name'];

        $this->username = $installed['username'] ?? $this->readEnvAny([
            'DB_USER', 'DB_USERNAME', 'MYSQL_USER', 'MYSQLUSER'
        ]) ?? $this->defaults['username'];

        $this->password = $installed['password'] ?? $this->readEnvAny([
            'DB_PASSWORD', 'DB_PASS', 'MYSQL_PASSWORD', 'MYSQLPASSWORD'
        ]) ?? $this->defaults['password'];

        $this->port = (int)($installed['port'] ?? $this->readEnvAny([
            'DB_PORT', 'MYSQL_PORT', 'MYSQLPORT'
        ]) ?? $this->defaults['port']);
    }

    public function getSettings(): array {
        return [
            'host' => $this->host,
            'db_name' => $this->db_name,
            'username' => $this->username,
            'password' => $this->password,
            'port' => $this->port,
        ];
    }

    public function getConnection(): PDO {
        if ($this->conn !== null) {
            return $this->conn;
        }
        try {
            $dsn = "mysql:host={$this->host};port={$this->port};dbname={$this->db_name};charset=utf8mb4";
            $this->conn = new PDO($dsn, $this->username, $this->password);
            $this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $this->conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            $this->conn->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
        } catch (PDOException $e) {
            error_log('DB connection error: ' . $e->getMessage());
            throw new Exception('Error de conexion a la base de datos');
        }
        return $this->conn;
    }
}
