<?php
/**
 * Database configuration — MariaDB/MySQL
 * Credentials are read from db_config.php (generated by install.php) or env vars.
 */
class Database {
    private string $host;
    private string $db_name;
    private string $username;
    private string $password;
    private int $port;
    private ?PDO $conn = null;

    private array $defaults = [
        'host'     => 'localhost',
        'db_name'  => 'cerrajeria_express',
        'username' => 'root',
        'password' => '',
        'port'     => 3306,
    ];

    private function readEnv(string $key): ?string {
        $value = getenv($key);
        if ($value !== false && $value !== '') {
            return (string)$value;
        }

        if (isset($_ENV[$key]) && $_ENV[$key] !== '') {
            return (string)$_ENV[$key];
        }

        if (isset($_SERVER[$key]) && $_SERVER[$key] !== '') {
            return (string)$_SERVER[$key];
        }

        return null;
    }

    public function __construct() {
        $installed = [];
        $configFile = __DIR__ . '/db_config.php';
        if (file_exists($configFile)) {
            $loaded = include $configFile;
            if (is_array($loaded)) {
                $installed = $loaded;
            }
        }

        $this->host     = $installed['host']     ?? $this->readEnv('DB_HOST')     ?? $this->defaults['host'];
        $this->db_name  = $installed['db_name']  ?? $this->readEnv('DB_NAME')     ?? $this->defaults['db_name'];
        $this->username = $installed['username'] ?? $this->readEnv('DB_USER')     ?? $this->defaults['username'];
        $this->password = $installed['password'] ?? $this->readEnv('DB_PASSWORD') ?? $this->defaults['password'];
        $this->port     = (int)($installed['port'] ?? $this->readEnv('DB_PORT')   ?? $this->defaults['port']);
    }

    public function getSettings(): array {
        return [
            'host' => $this->host,
            'db_name' => $this->db_name,
            'username' => $this->username,
            'password' => $this->password,
            'port' => $this->port,
        ];
    }

    public function getConnection(): PDO {
        if ($this->conn !== null) {
            return $this->conn;
        }
        try {
            $dsn = "mysql:host={$this->host};port={$this->port};dbname={$this->db_name};charset=utf8mb4";
            $this->conn = new PDO($dsn, $this->username, $this->password);
            $this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $this->conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            $this->conn->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
        } catch (PDOException $e) {
            error_log('DB connection error: ' . $e->getMessage());
            throw new Exception('Error de conexion a la base de datos');
        }
        return $this->conn;
    }
}
